/* ./pages/index.js               */
import Head from "next/head";
import Image from "next/image";
import styles from "./Home.module.css";
import React, { useState } from "react";
import { Layout } from "../layout";
import Hero from "../lpage/Hero";
import About from "../About/About";
import Offers from "../lpage/Offers";
import CustomerEmpowerment from "../lpage/customerEmpower";
import StaffMang from "../lpage/staffManagement";
import Footer from "../lpage/footer";
import Ebook from "../lpage/ebook";
import Pricing from "../lpage/pricing";
import Babaoja from "../lpage/Babaoja";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Wakanda Business</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className={styles.container}>
          <Head>
            <title>Wakanda Business</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main>
            <Hero />
            {/* <About/> */}
            <Offers />
            <CustomerEmpowerment />
            <StaffMang />
            <Pricing />
            <Babaoja />
            <Ebook />
          </main>
        </div>
      </Layout>
    </div>
  );
}
